### ISSUE TITLE
What makes this “official”?

### ISSUE THREAD

**Issue by Kwpolska** [sdispater/pytzdata#6]
This repo calls itself

> Official timezone database for Python.

What makes it so? The Olson database is not “official” in any kind. Does this project have an endorsement of the Python core team?

**Comment by KostyaEsmukov** [comment]
This proclamation is questionable indeed.

**Comment by sdispater** [comment]
I just updated the description. Sorry for the misunderstanding.

While the Olson database is not really official it is the de facto timezone database used by a lot of projects and systems out there. But I agree the description was misleading. This is now fixed.

**Comment by jayaddison** [comment]
@sdispater sorry for this ping: you removed the word 'official' from the package description; would you be OK to also remove it from the `pytzdata` GitHub repository description?

(context: I was briefly confused based on the description of this repository on GitHub, and a description of the `tzdata` package on PyPi as 'official'.  if _neither_ of them had been described that way, then they might be easier to differentiate)
