### ISSUE TITLE
wrong time zone offsets for St. Johns, Newfoundland and Marquesas

### ISSUE THREAD

**Issue by rghgit** [sdispater/pytzdata#9]
Wrong offsets in 2018.9: 
```
Canada/Newfoundland          -05:10           must be: -03:30
America/St_Johns             -05:10           must be: -03:30
Pacific/Marquesas            -11:10           must be: -09:30
```

These errors may be due to typos:
-05:10 = -**3**10 minutes  while  -03:30 = -**2**10 minutes
-11:10 = -**6**70 minutes while  -09:30 = -**5**70 minutes

**Comment by sdispater** [comment]
As far as I know the offsets are correct. Here are examples using `pendulum` (which uses `pytzdata`):

```python
>>> import pendulum
>>> pendulum.now("Canada/Newfoundland").isoformat()
'2019-02-28T17:22:09.576059-03:30'
>>> pendulum.now("Pacific/Marquesas").isoformat()
'2019-02-28T11:22:38.307084-09:30'
```

Where did you get these offsets from?

**Comment by rghgit** [comment]
Withdrawn with my apologies! The data is correct. The bug was in my internal code.
